import type { ReactNode } from 'react'

function DiagramFigure({ number, title, type, children, caption }: { number: number; title: string; type: string; children: ReactNode; caption?: string }) {
  return <figure className="article-diagram"><figcaption><span>fig {number} · {title}</span><span>mermaid · {type}</span></figcaption><div className="diagram-scroll" tabIndex={0} aria-label={`${title}, diagram; scroll horizontally on small screens`}>{children}</div>{caption && <p>{caption}</p>}</figure>
}

function Arrow({ x1, x2, y, pink = false, dashed = false }: { x1: number; x2: number; y: number; pink?: boolean; dashed?: boolean }) {
  const direction = x2 > x1 ? 1 : -1
  return <g className={pink ? 'diagram-accent' : ''}><line x1={x1} y1={y} x2={x2 - direction * 7} y2={y} stroke="currentColor" strokeWidth={pink ? 2 : 1} strokeDasharray={dashed ? '5 4' : undefined} /><polygon points={`${x2},${y} ${x2 - direction * 7},${y - 3.5} ${x2 - direction * 7},${y + 3.5}`} fill="currentColor" /></g>
}

export function FlowDiagram() {
  const stages = [{ x: 0, text: 'ingest', meta: '200 · cpu', weight: 200 }, { x: 120, text: 'chunk', meta: '300 · cpu', weight: 300 }, { x: 230, text: 'extract', meta: '500 · onnx', weight: 500 }, { x: 460, text: 'link', meta: '600 · graph', weight: 600 }, { x: 570, text: 'index', meta: '800 · done', weight: 800 }]
  return <DiagramFigure number={1} title="the ingest path" type="flowchart LR" caption="ink for the default path, pink for the expensive one. no fills, no rounded corners."><svg viewBox="0 0 680 230" width="680" height="230" role="img" aria-labelledby="flow-title flow-desc"><title id="flow-title">The ingest path</title><desc id="flow-desc">Ingest, chunk, and extract lead to a confidence check. Scores at least 0.65 go directly to link and index. Other spans escalate to an LLM before linking.</desc><image href="/design/writing-flow-light.svg" width="680" height="230" className="diagram-light-asset" /><image href="/design/writing-flow-dark.svg" width="680" height="230" className="diagram-dark-asset" />{stages.map(stage => <g key={stage.text}><text x={stage.x} y="54" className="diagram-meta">{stage.meta}</text><text x={stage.x} y="87" fontSize="20" fontWeight={stage.weight} letterSpacing="-.03em">{stage.text}</text></g>)}<text x="395" y="31" fontSize="10" textAnchor="middle">sure ≥ .65 ?</text><text x="434" y="70" className="diagram-meta">yes</text><text x="402" y="138" className="diagram-accent" fontSize="10">no</text><text x="395" y="195" fontSize="14" fontWeight="800" textAnchor="middle">llm · 910ms</text></svg></DiagramFigure>
}

export function SequenceDiagram() {
  const actors = ['user', 'orchestrator', 'agent', 'mcp tool']
  return <DiagramFigure number={2} title="one gated tool call" type="sequenceDiagram" caption="solid for calls, dashed for replies. the one step worth noticing gets the pink."><svg viewBox="0 0 680 330" width="680" height="330" role="img" aria-labelledby="sequence-title sequence-desc"><title id="sequence-title">One gated tool call</title><desc id="sequence-desc">The user asks the orchestrator. It plans a DAG for the agent, which makes a gated MCP tool call with a reason. The tool returns a result, the agent streams, and the orchestrator answers.</desc>{actors.map((actor, i) => <g key={actor}><rect x={15.5 + i * 180} y=".5" width="110" height="32" fill="none" stroke="currentColor" /><text x={70.5 + i * 180} y="20" fontSize="12" textAnchor="middle">{actor}</text><line x1={70.5 + i * 180} y1="33" x2={70.5 + i * 180} y2="320" className="diagram-hairline" stroke="currentColor" strokeDasharray="3 4" /></g>)}<Arrow x1={71} x2={250} y={70} /><Arrow x1={251} x2={430} y={110} /><Arrow x1={431} x2={610} y={160} pink /><Arrow x1={610} x2={430} y={210} dashed /><Arrow x1={430} x2={250} y={250} dashed /><Arrow x1={250} x2={70} y={290} dashed />{[{ x: 160, y: 61, label: 'ask' }, { x: 340, y: 101, label: 'plan · dag' }, { x: 520, y: 151, label: 'call(reason=…)' }, { x: 520, y: 203, label: 'result' }, { x: 340, y: 241, label: 'stream' }, { x: 160, y: 281, label: 'answer' }].map(item => <text key={item.label} x={item.x} y={item.y} fontSize="11" textAnchor="middle" fontWeight={item.label === 'answer' ? 800 : 400}>{item.label}</text>)}<rect x="470" y="170" width="100" height="18" fill="var(--accent)" /><text x="520" y="183" fontSize="10" textAnchor="middle" className="diagram-chip-text">gated</text></svg></DiagramFigure>
}

export function StateDiagram() {
  const states = [{ x: 60.5, y: 40.5, label: 'pending' }, { x: 250.5, y: 40.5, label: 'running' }, { x: 440.5, y: 40.5, label: 'completed' }, { x: 250.5, y: 140.5, label: 'failed' }]
  return <DiagramFigure number={3} title="a node in the dag panel" type="stateDiagram-v2"><svg viewBox="0 0 680 200" width="680" height="200" role="img" aria-labelledby="state-title state-desc"><title id="state-title">A node in the DAG panel</title><desc id="state-desc">Pending nodes become running when dependencies are met. They complete on success or fail on error. Failed nodes can retry at most twice.</desc><circle cx="14" cy="60" r="7" fill="currentColor" />{states.map(state => <g key={state.label}><rect x={state.x} y={state.y} width="110" height="40" fill="none" stroke="currentColor" strokeWidth={state.label === 'completed' ? 2 : 1} /><text x={state.x + 55} y={state.y + 26} fontSize="12" fontWeight={state.label === 'completed' ? 800 : 400} textAnchor="middle">{state.label}</text></g>)}<circle cx="640" cy="60" r="10" fill="none" stroke="currentColor" /><circle cx="640" cy="60" r="5" fill="currentColor" /><Arrow x1={22} x2={60} y={60} /><Arrow x1={171} x2={250} y={60} /><Arrow x1={361} x2={440} y={60} /><Arrow x1={551} x2={630} y={60} /><line x1="305" y1="81" x2="305" y2="138" stroke="currentColor" /><polygon points="305,140 301.5,133 308.5,133" fill="currentColor" /><text x="211" y="51" className="diagram-meta" textAnchor="middle">deps met</text><text x="401" y="51" className="diagram-meta" textAnchor="middle">ok</text><text x="312" y="113" className="diagram-meta">error</text><g className="diagram-accent"><polyline points="250,160 115,160 115,84" fill="none" stroke="currentColor" strokeWidth="2" /><polygon points="115,81 111,89 119,89" fill="currentColor" /><text x="130" y="175" fontSize="10">retry ≤ 2</text></g></svg></DiagramFigure>
}
